### ISSUE TITLE
Limitation of use not compatible with MIT license

### ISSUE THREAD

**Issue by ptashek** [somefunAgba/ModernPIDControlSS#1]
The about page specifies the code is licensed under the MIT license, which allows for unrestricted use in proprietary software including for commercial purposes. The limitation of use notice on the landing page is therefore incompatible with the stated license, and should be removed (or the code re-licensed) to avoid confusion.

**Comment by somefunAgba** [comment]
Thanks @ptashek  for the notice. I have rectified this on the landing page.
